# Generated by Django 3.2.9 on 2021-11-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('description', models.TextField(verbose_name='description')),
                ('logo', models.FileField(default='default_logo.png', upload_to='uploads/', verbose_name='url')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
