# Generated by Django 3.2.9 on 2021-12-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='organization/logo/', verbose_name='logo'),
        ),
    ]
